Update to latest version of http-signature
Attempting to validate signatures from clients with the latest
http-signature was resulting in errors:
 InvalidHeaderError: signature was empty
Due to changes in http-signature. Changing the dependency to the latest
0.11.x http-signature fixes this issue.